// products
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const DELETE_FROM_CART = 'DELETE_FROM_CART'
export const SET_ORDER_HISTORY = 'SET_ORDER_HISTORY'
export const SET_SEARCH_PHRASE = 'SET_SEARCH_PHRASE'
export const RESET_CART = "RESET_CART"

// user
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const SET_USER_TOKEN = 'SET_USER_TOKEN'
export const SET_LOGGED_IN = 'SET_LOGGED_IN'
export const SET_USER_LOADING = 'SET_USER_LOADING'
export const SET_WRONG_USER_DETAILS = 'SET_WRONG_USER_DETAILS'
