// products
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const DELETE_FROM_CART = 'DELETE_FROM_CART'
export const SET_CURRENT_ORDER = 'SET_CURRENT_ORDER'
export const SET_SEARCH_PHRASE = 'SET_SEARCH_PHRASE'
export const SET_CART_OBJECT = 'SET_CART_OBJECT'

// user
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const SET_USER_TOKEN = 'SET_USER_TOKEN'
export const SET_LOGGED_IN = 'SET_LOGGED_IN'
