export const LOGIN_USER_MUTATION = 'LOGIN_USER_MUTATION';
export const EDIT_USER_MUTATION = 'EDIT_USER_MUTATION';
export const LOGOUT = 'LOGOUT';
export const ADD_PRODUCTS_MUTATION = 'ADD_PRODUCTS_MUTATION'
export const ADD_PRODUCT_ORDER = 'ADD_PRODUCT_ORDER'
export const CALCULATE_PRICE = 'CALCULATE_PRICE'
export const ADD_USER_HISTORY = 'ADD_USER_HISTORY' 