export const LOGIN_USER_MUTATION = 'LOGIN_USER_MUTATION';
export const EDIT_USER_MUTATION = 'EDIT_USER_MUTATION';
export const LOGOUT = 'LOGOUT';
export const ADD_PRODUCTS_MUTATIONS = 'ADD_PRODUCTS_MUTATIONS'