// products
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const ADD_TO_CART = 'ADD_TO_CART'
export const SET_CURRENT_ORDER = 'SET_CURRENT_ORDER'
export const SET_ORDER_HISTORY = 'SET_ORDER_HISTORY'
export const SET_SEARCH_PHRASE = 'SET_SEARCH_PHRASE'

// user
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const SET_USER_TOKEN = 'SET_USER_TOKEN'
export const SET_LOGGED_IN = 'SET_LOGGED_IN'
export const SET_USER_LOADING = 'SET_USER_LOADING'
